// <auto-generated />
namespace Simran_hospital.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class volunteer_opp : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(volunteer_opp));
        
        string IMigrationMetadata.Id
        {
            get { return "202103251114166_volunteer_opp"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
