// <auto-generated />
namespace team2Geraldton.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Initialsetup : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Initialsetup));
        
        string IMigrationMetadata.Id
        {
            get { return "202104111545546_Initial setup"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
