// <auto-generated />
namespace GeraldtonHospital_v1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class DonorTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DonorTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202104070707111_DonorTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
