// <auto-generated />
namespace hospitalPrj.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addCollaspnetuser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addCollaspnetuser));
        
        string IMigrationMetadata.Id
        {
            get { return "202104100458172_addColl-aspnetuser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
