// <auto-generated />
namespace team2Geraldton.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AvgRateadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AvgRateadded));
        
        string IMigrationMetadata.Id
        {
            get { return "202104252339008_AvgRate added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
