// <auto-generated />
namespace hospital_prj.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class create_Db2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(create_Db2));
        
        string IMigrationMetadata.Id
        {
            get { return "202104091421071_create_Db2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
